{
  "aliceMinVersion": "1.0.0-b5",
  "author": "philipp2310",
  "category": "information",
  "conditions": {
    "lang": [
      "en",
      "de"
    ]
  },
  "desc": "Control your fritz!box, and show its status!",
  "icon": "fab fa-battle-net",
  "maintainers": [],
  "name": "FritzBox",
  "pipRequirements": [
    "fritzconnection==1.7.0"
  ],
  "speakableName": "Fritz Box",
  "systemRequirements": [
    ""
  ],
  "version": "0.0.3"
}